plugins {
    id 'eclipse'
    id 'java-library'
}

repositories {
    mavenCentral()
}

group = 'org.ta4j'
version = '0.16-SNAPSHOT'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc) {
    options.encoding = 'UTF-8'
}

test {
    onlyIf {
        project.hasProperty("ta4jTests")
    }
}

dependencies {
    api project(':ta4j-core')
    api 'com.opencsv:opencsv:5.7.1'
    api 'org.jfree:jfreechart:1.5.3'
    api 'com.google.code.gson:gson:2.10'
    implementation 'ch.qos.logback:logback-classic:1.5.18'
    testImplementation 'junit:junit:4.13.2'
}

description = 'Ta4j Examples'
